CCExtractor/Flood_Mobile

CONTRIBUTING.md, packages/flutter_client_sse/pubspec.lock
Fixes #40 
Update contributing.MD
=> Feature/update contributing.md

android/app/build.gradle, android/app/src/main/AndroidManifest.xml, android/build.gradle, lib/Components/filter_by_status.dart, lib/Pages/torrent_screen.dart, lib/Provider/filter_provider.dart, lib/main.dart, pubspec.lock
Fixes #26 
**Describe the changes you have made in this PR :**
- Added filter torrent based on the completion status feature in the app.
**Filter feature working demo video:**
https://user-images.githubusercontent.com/73401649/154160536-39d8c8e0-8c29-4f8b-b4c4-ab7bf783029b.mp4
=> feat: Adds filter torrent based on the completion status feature

android/app/build.gradle, android/app/src/main/AndroidManifest.xml, android/build.gradle, lib/Components/filter_by_status.dart, lib/Components/settings_text_field.dart, lib/Pages/settings_screen.dart, lib/Pages/torrent_screen.dart, lib/main.dart, pubspec.lock
Fixes #69 
**Describe the changes you have made in this PR:** 
- Added feature to display applied filter information on the home screen
**Feature working demonstration video:**
https://user-images.githubusercontent.com/73401649/153950877-e09999f5-8eab-487c-a606-26f799800d3f.mp4
=> Issue 69: Display applied filter information on the home screen

.github/workflows/dart.yml, android/app/build.gradle, android/build.gradle, android/gradle/wrapper/gradle-wrapper.properties, lib/Components/add_torrent_sheet.dart, lib/Components/filter_by_status.dart, lib/Pages/torrent_screen.dart, pubspec.lock
Fixes: Resolves CI build Issues
=> fix: Merge master changes to develop

CONTRIBUTING.md
=> Small installation error

lib/Components/add_torrent_sheet.dart, lib/Components/delete_torrent_sheet.dart, lib/Components/flood_snackbar.dart, lib/Pages/settings_screen.dart
Fixes #30 
The PR includes the feature of adding snackbar on:
- adding new torrent
- deleting a torrent
- adding a new user
- saving settings
=> [Feat] Add snackbar for multiple events

CONTRIBUTING.md
There are some UI changes in the qBittorrent app, we can setup the Web UI only after clicking the settings button, it is not yet updated in the documentation, In the documentation its saying that Web UI setup can be done after clicking the preferences - but it is wrong. I saw that some people getting confused about that and asking about it in the slack channel, So I thought of updating it in the documentation. 
I hope that this contribution will help the community, if there is changes needing to be made in the commit, kindly inform me
Thank You.
=> Updated the Contributing.md file regarding the qBittorent UI changes

lib/Components/filter_by_status.dart, lib/Components/notification_popup_dialogue_container.dart, lib/Components/torrent_tile.dart, lib/Pages/torrent_content_screen.dart
Fixes #140 fix theme lightmode
Make it clearly visible in light and dark mode
Above changes that i made
=> Issue 140 fix some colors in lightmode theme 

lib/Pages/about_screen.dart
Issue : In small devices about us screen give overflow error because we can not scroll about up page so i make in scrollable when app runs in small devices
=> fix overflow issue on about us screen

lib/Api/torrent_api.dart, lib/Components/torrent_tile.dart
Fixes #42 
I have resolved the Partially Implemented Check Hash #42 issue.
- Added a snackbar to show the result of checkTorrentHash method.
- Changed the checkTorrentHash method to return boolean value.
Screenshots-
=> Resolved check hash issue

lib/Components/RSSFeedHomePage.dart, lib/Components/add_torrent_sheet.dart, lib/Components/bottom_floating_menu_button.dart, lib/Components/delete_torrent_sheet.dart, lib/Pages/settings_screen.dart
When new snackbar is generate at that time old snackbar takes a time to hide. 
https://user-images.githubusercontent.com/91112485/211524158-baddbed9-c939-4d71-aada-8f03480bef06.mp4
So in this PR i close old snackbar before get new snackbar .
=> fix multiple time snackbar open after press

lib/Components/RSSFeedHomePage.dart, lib/Components/add_automatic_torrent.dart, lib/Components/bottom_floating_menu_button.dart, lib/Components/torrent_tile.dart, lib/Pages/home_screen.dart
Fixed the Theme changing error to the light version
The error was due to wrong theme usage which lead to unusual UI.
=> Fixed light theme colour issue for bottom sheet

lib/Api/event_handler_api.dart, lib/Pages/torrent_screen.dart
Fixes #171 
Update filter information after deleting any torrent
https://user-images.githubusercontent.com/91112485/215077859-28f7a743-7431-417a-9a00-2989e6871652.mp4
=> fix filter track update on delete torrent

lib/Components/toast_component.dart, lib/Pages/home_screen.dart
issue #162 
If the user accidentally presses the back button, the app will close. To fix this, the user must press the back button twice continuously to exit the app. A toast message will also appear if the user only taps the back button once.
=> notify user when press back button for exit

lib/Components/notification_popup_dialogue_container.dart
Fixes #174 
I called `getNotifications` whenever user open notification dialogue box so it's updated with lestest notifications
=> Fix the new torrent download list in the notification dialog.

lib/Components/RSSFeedHomePage.dart, test/rss_feed_homepage_widget_test.dart
Fixes #177 
I added required validation that are present in flood web ui but not in flood mobile application. This validation will trigger when user submit the form .
It's look like this :
=> Add validation on feeds and download rules

lib/Pages/settings_screen.dart
Fixes #185 
I add snackbar after successfully set upload and download speed.
=> add snackbar on set speed

lib/Api/event_handler_api.dart, lib/Api/torrent_api.dart, lib/Components/add_tag_dialogue.dart, lib/Components/filter_by_status.dart, lib/Components/torrent_tile.dart, lib/Pages/home_screen.dart, lib/Pages/torrent_screen.dart, lib/Provider/api_provider.dart, lib/Provider/filter_provider.dart
Fixes #29 
User can able to filter by existing tags
=> add filter by tag feature

lib/Components/RSSFeedHomePage.dart, lib/Constants/theme_provider.dart
Fixes #149 
fix theme issue at RSSFeedHomePage by declare global theme variable `disabledColor` and `dividerColor`
=> slove theme issue at RSSFeedHomePage

lib/Pages/torrent_screen.dart, lib/Provider/filter_provider.dart, test/api_provider_unit_test.dart, test/client_provider_test.dart, test/color_provider_unit_test.dart, test/filter_provider_unit_test.dart, test/graph_provider_unit_test.dart, test/multiple_select_torrent_provider_test.dart
**Describe the changes you have made in this PR -**
This pull request introduces comprehensive unit testing for the newly added features, ensuring their quality and reliability. By implementing rigorous testing procedures, we enhance the stability of the codebase, reduce the chances of regression issues, and foster a smoother development process. I designed and implemented a robust unit testing framework to cover the new features thoroughly.
Create unit test case for following files :
- `client provider`
- `graph provider`
- `multiple select torrent provider`
- `color provider`
- `filter provider`
- Additionally, the issue with `api_provider_unit_test.dart` failing to run has been resolved.
=> implement unit testing for new added features

test/model_test/client_settings_model_test.dart, test/model_test/current_user_detail_model_test.dart, test/model_test/download_rate_model_test.dart, test/model_test/feeds_content_model_test.dart, test/model_test/notification_content_model_test.dart, test/model_test/notification_model_test.dart, test/model_test/regitster_user_model_test.dart, test/model_test/rss_feed_model_test.dart, test/model_test/single_feed_and_response_model_test.dart, test/model_test/single_rule_model_test.dart, test/model_test/torrent_content_model_test.dart, test/model_test/torrent_model_test.dart
This pull request introduces the implementation of test cases for all models within the [Your Company Name] project. The primary objective is to enhance the reliability and performance of our models by ensuring comprehensive testing coverage. By implementing these test cases, we aim to deliver high-quality solutions to our valued customers and provide a robust user experience.
- Created a new directory 'model_test' within the project structure to house all the model test case files.
- Developed individual test cases for each model, covering various scenarios and use cases.
- I ensured that all the test cases run properly and no one fails.
=> implement test cases for all models

lib/Api/event_handler_api.dart, lib/Blocs/language_bloc/language_bloc.dart, lib/Blocs/theme_bloc/theme_bloc.dart, lib/Pages/home_screen/widgets/rss_feed_home_page.dart
**Describe the changes you have made in this PR:**
I have addressed several issues during the testing of app:
- Resolved an issue where the download would stop when the `"wifi-only"` setting was enabled while downloading using mobile data.
- Fixed a `SharedPreferences` error that was appearing in the debug log.
- Fixed the problem where the RSS feed was not updating properly.
=> Fix some small issues
