CCExtractor/Flood_Mobile

lib/Components/settings_text_field.dart, lib/Pages/settings_screen.dart
Fixes #56 
Keyboard of input fields in settings page are not set correctly.
for alphabetic, it's showing numeric and vice versa.
Fixed this issue. Now for alphabetic will show alphabetic and for numerical will show numerical
before:
after:
=> fixed: input field is numerical when should be texual

lib/Components/settings_text_field.dart
Fixes #61 
When user toggle to dark mode, the label in setting input field will be more visible (white54 instead of shadow black in dark mode. in light mode shadow black will be shown as before)
Before:
After:
=> in dark mode, label will be more visible

lib/Components/add_torrent_sheet.dart
Fixes #71 
**Describe the changes you have made in this PR:**
- Made the container of the add torrent screen rounded to make the UI of the screen similar to the UI it has before the implementation of light/dark mode in the app.
**Screenshots of the changes:**
<table>
<tr>
<td align="center"><img src= "https://user-images.githubusercontent.com/73401649/153958310-42a042ef-a12f-4a9b-97cd-5e651ab413df.jpg" width="250"> <br /><b>Earlier screen before implementing the changes in this PR in dark mode</b></a><br /></td>
<td align="center"><img src= "https://user-images.githubusercontent.com/73401649/153958072-c83f086c-27ae-4276-a47b-aba8f393d3f7.jpg" width="250"><br /><b>Add torrent screen after implementing the changes made in this PR in dark mode</b></a><br /></td>
</tr>
</table>
<table>
<tr> …
=> Solves simple UI bug in add torrent screen

lib/Components/settings_text_field.dart, pubspec.lock
Fixes #79 
Resolves visibility issue in the LabelText of different options of the settings screen in the dark mode of the app.
<table>
<tr>
<td align="center"><img src= "https://user-images.githubusercontent.com/73401649/161582649-cb79fa71-45d2-4935-bf58-70e4f8eaaedc.jpg" width="250"> <br /><b>Earlier screen before implementing the changes in this PR</b></a><br /></td>
<td align="center"><img src= "https://user-images.githubusercontent.com/73401649/161582280-15429141-f8e7-44b8-95a2-f9cb0457cbfe.jpg" width="250"><br /><b>Screen after implementing the changes made in this PR</b></a><br /></td>
</tr>
</table>
=> fix: Resolves visibility issue in the LabelText of settings screen

lib/Components/settings_text_field.dart
Fixes #83 
Resolves incompatible keyboard type for different TextFields of the settings option.
<table>
<tr>
<td align="center"><img src= "https://user-images.githubusercontent.com/73401649/161758725-6e71dd87-6c6a-431e-9793-a6c83f3e056c.jpg" width="250"> <br /><b>Incompatible Input keyboard (Screen-1)</b></a><br /></td>
<td align="center"><img src= "https://user-images.githubusercontent.com/73401649/161760289-bbf2e1de-ef3b-4343-80fa-8d8dd33a35cb.jpg" width="250"> <br /><b>Changed compatible Input keyboard (Screen-1)</b></a><br /></td>
<td align="center"><img src= "https://user-images.githubusercontent.com/73401649/161759057-d2d1d0e4-aef0-4ae3-babc-de9aa16b56ad.jpg" width="250"><br /><b>Incompatible Input …
=> fix: Incompatible keyboard type for different TextFields of the settings option.

lib/Api/event_handler_api.dart
Closes #121
`torrentLength` is being initialized to an empty string, which is causing a problem when we are passing it to `int.parse` as soon as the first torrent has been added. Initializing it to zero solves that problem.
=> Fix an issue of invalid number

lib/Components/RSSFeedHomePage.dart
Fixes #112 
As mentioned in the issue, I have added snackbar when user adds a feed or a rule, to provide confirmation that it has been added successfully.
=> Add snackbar for adding feed and rule

lib/Components/bottom_floating_menu_button.dart, lib/Pages/settings_screen.dart
Fixes: #114 
1. Fixed a snackbar display when torrent was added through Bottom sheet using FAB
2. Fixed a snackbar display when user was added because the error was in Port number parsing.
=> Snackbar for add new user and add new torrent not working

lib/Components/RSSFeedHomePage.dart
Fixes #131  Theme bug in rss-feed and download rules page in light mode.
Fix boundaries visibility on existings feeds and existing rules in light .
Screenshots of the changes :
=> Fix boundaries visibility on existings feeds and existing rules in light 

lib/Components/RSSFeedHomePage.dart
Fixes #127 Add snackbar on deleting a rss-feed/download rule. 
Screenshots of the changes -
=> Add snackbar on deleting a rss-feed/download rule.

lib/Components/RSSFeedHomePage.dart, lib/Components/torrent_tile.dart
fix followings text overflow issues in rss feed and torrent details page
Screenshots of the changes  -
=> fix text overflow in rss feed and torrent details

lib/Components/torrent_content_tile.dart, lib/Model/torrent_content_model.dart
Add multiple formate video and audio in video stream screen
In video stream screen only MP4 video extention is supported. I added mp3, wav, mkv, mov, webm files for play video.
=> add multiple formate video and audio in video stream screen

lib/Components/bottom_floating_menu_button.dart
F# Fixes #128 
- Describe the changes you have made in this PR :
Since the checkboxlisttile was in a bottomSheet it wasnt working as expected, now all checkboxlisttiles are wrapped with statefulbuilder which will listen to checkbox onclick even and repaints only the checkBox instead of whole sheet.
https://user-images.githubusercontent.com/93595710/212462379-5351b4d9-0898-41a3-9b3f-01b385c88b95.mp4
=> fix: make checkbox clearly visible onclick

lib/Components/flood_snackbar.dart
Fixes: Text overflow issue in snackbar #163
- Added overflow property to Text widget in snackbar.
- Wrapped Text widget in snackbar with an Expanded widget.
=> Snackbar overflow issue resolved

lib/Components/logout_alert.dart
Fixes #187 
Make alignment of `spaceEvenly` so if there is blank space then `spaceEvenly` is looks nice.
=> fix button alignment in logout_alert_dialogue

lib/Pages/torrent_screen.dart
Fixes #180 
- In this PR i add new features when user applied any filter and correspond filtered torrent is empty then user see `no torrent to display` text and `clear filter` button that clear applied filter. 
- First `countDisplayTorrent` function count the applies filter number. if number is zero then user can see this feature.
https://user-images.githubusercontent.com/91112485/217017797-905747e6-df01-4fb1-b155-81805b7b8e29.mp4
=> Add clear filter feature on empty filtered torrent

lib/Api/auth_api.dart, lib/Components/user_list.dart, lib/Constants/theme_provider.dart, lib/Pages/home_screen.dart, lib/Pages/settings_screen.dart, lib/Pages/splash_screen.dart, lib/Provider/api_provider.dart, lib/Provider/user_detail_provider.dart, test/user_detail_provider_unit_test.dart
Fixes #129 
Tasks achieved in this PR -
1. **Display the list of users**: Wrote a function `getUsersList` in `AuthApi` to find the list of users (Refer the attached picture).
2. **Delete a user**: If the current user is an admin, they will be able to delete any of the other users with a single tap. Wrote a function `deleteUser` in `AuthApi` which handles the API.
3. **Restrict non admin users from updating Authentication settings**: I check on Flood web app, if the user is not an admin, they are not able to change any of the settings under Authentication head, but this was not the case in the mobile app. So, I have handled the case when user is not an admin (Refer the attached picture).
4. Update tests for `UserDetailsProvider`: Because now username is also getting stored in …
=> issue 129 show list of users in setting screen

lib/Components/onboarding/onboarding.dart
Fixes #183 
- The text and the skip button at top of the screen on the onboarding page were overlapping with the container below. I've shifted them above by adding some padding so this doesn't happen
=> Fixed the overlapping text and skip button

lib/Components/RSSFeedHomePage.dart, lib/Constants/theme_provider.dart
Fixes #196 
**Describe the changes you have made in this PR -**
fix theme issue at `RSSFeedHomePage` by declare global theme variable `disabledColor` and `dividerColor`
Screenshots of the changes  -
**- Light Mode**
**- Dark Mode**
=> fixed RSS-Feed's browse feeds theme issue

lib/Components/RSSFeedHomePage.dart
Fixes #198 
- added controller.clear() method to clear the text textFields
- added two functions that handles the clearing of the fields in Feed tab and Rules tab
- added comments for the controller functionality
https://user-images.githubusercontent.com/93595710/223111004-374b04ed-f7e8-408e-9d88-effcb66ef84e.mp4
https://user-images.githubusercontent.com/93595710/223111005-22637e34-160b-4327-952f-57c07a3cdf5f.mp4
=> fix: clear the textFields after saving on rssfeedhomepage

lib/Api/torrent_api.dart, lib/Components/delete_torrent_sheet.dart, lib/Components/torrent_tile.dart, lib/Pages/home_screen.dart, lib/Pages/torrent_screen.dart, lib/Provider/multiple_select_torrent_provider.dart
Fixes #195 
- Made the notification for a downloading torrent dismiss automatically whenever we delete the corresponding torrent
- I hade made this by adding `AwesomeNotifications().dismiss(id);` in [torrent_api.dart](https://github.com/CCExtractor/Flood_Mobile/blob/master/lib/Api/torrent_api.dart), which basically dismisses the notification for the corresponding downloading torrent by the given id or index of the torrent.
Demo of the changes -
https://github.com/CCExtractor/Flood_Mobile/assets/91112485/58bed85d-3ed1-468d-98f4-ae2439d13b6a
=> added the feature to dismiss the notification when the torrent is deleted

lib/Api/client_api.dart, lib/Components/RSSFeedHomePage.dart
Fixes #197 
Gist: Checking if the backend is connected when clicking on the save option if not show a snack bar with a msg.
Implementation:
- Created a `checkClientOnline` function that makes calls to the backend and checks whether the status code is 200 or not.
- The function is implemented in the save button of the RSS feed bottom sheet
Demo of the changes-
https://github.com/CCExtractor/Flood_Mobile/assets/91112485/4d4dee61-b75e-48f0-bd27-29a12291f958
=> fix: RSSfeed get added without backend connection

lib/Pages/settings_screen.dart
Fixes #60 
I need to fix the issue of being unable to update multiple fields on the settings page. The problem arises from multiple invocations of the `didChangeDependencies` method. Whenever a change occurs in the `clientSettings`, the `didChangeDependencies` method is called, which overwrites the user-entered values. So, I have set `listen: false` for `ClientSettingsProvider` to prevent the reinitialization of every field when `clientSettings` changes.
=> fix unable to update many fields in setting page issue

lib/Api/event_handler_api.dart
When a user adds a torrent file, the downloading status is declared multiple times in the torrent status. As a result, there is always one downloading status in the torrent status, preventing us from seeing the play icon on the torrent tile.
In this pull request, I addressed this issue by checking each torrent's status. If both 'stopped' and 'downloading' statuses are present in the torrent status, it indicates a duplicate status, and I removed it.
=> fix play/pause button issue on add torrent by file

lib/Components/dark_transition.dart, lib/Constants/theme_provider.dart, lib/Pages/home_screen.dart, lib/Pages/login_screen.dart, lib/Pages/splash_screen.dart, lib/Route/route_generator.dart, lib/main.dart, test/widget_test/home_screen_widget_test.dart
**Describe the changes you have made in this PR -**
- This pull request implements theme persistence throughout the app to ensure that the selected theme persists even when the app is closed and reopened. This feature provides a consistent user experience by remembering the chosen theme.
I stored the theme change value in `SharedPreferences` and utilized it when required.
Additionally, ensured that the theme on the `splash screen` and `login screen` remains the same as the previously selected theme.
- Tested the app thoroughly to ensure that the selected theme persists even after closing and reopening the app.
- Verified that the app maintains the selected theme across different screens.
=>  Implement theme persistence throughout your app
